server:
  port: 8761

spring:
  application:
    name: eureka8761

#  security:
#    user:
#      name: user
#      password: 123

eureka:
  instance:
    instance-id: eureka8761
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
    register-with-eureka: false #不把自己注册到微服务上
    fetch-registry: false #不从微服务上获取信息
  server:
    enable-self-preservation: false
