server:
  port: 8001

spring:
  application:
    name: product8001

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/wechat?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: cyj7416146
    driver-class-name: com.mysql.jdbc.Driver


eureka:
  instance:
    instance-id: product8001
    prefer-ip-address: true
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/

